feat: use gravatar source as comment's avatar
halo-dev/plugin-comment-widget pull request #111
Opened 2024-04-03 19:56 UTC by mashirot

see https://github.com/halo-dev/halo/pull/5642
see #97 

两个不同邮箱，相同头像

效果：
![image](https://github.com/halo-dev/plugin-comment-widget/assets/52254895/3b61eaec-4cca-4425-8735-827d3f06ba72)

2024-04-04 09:15 UTC, mashirot commented
@JohnNiang @ruibaby 需要一些协助
请看一下自定义模型是否存在问题，以及组件设置界面的编写流程，这个项目好像没有引入vue

2024-04-04 09:26 UTC, guqing requested changes

2024-04-04 09:26 UTC, guqing commented on src/main/java/run/halo/comment/widget/CommentWidgetSetting.java
> +public class CommentWidgetSetting extends AbstractExtension {
不需要这个自定义模型吧 使用插件设置表单即可 你可以理解为为了一个评论设置加了一张表的操作 这属于大材小用了 参考： https://docs.halo.run/developer-guide/form-schema

2024-04-04 10:03 UTC, mashirot commented on src/main/java/run/halo/comment/widget/CommentWidgetSetting.java
> +public class CommentWidgetSetting extends AbstractExtension {
https://github.com/halo-dev/halo/pull/5642#discussion_r1550705871

不是很懂这个评论组件设置，指的就是评论设置吗

2024-04-04 12:05 UTC, guqing commented on src/main/java/run/halo/comment/widget/CommentWidgetSetting.java
> +public class CommentWidgetSetting extends AbstractExtension {
指的是评论插件的设置表单，参考插件 [plugin.yaml 的文档之插件设置](https://docs.halo.run/developer-guide/plugin/basics/manifest#:~:text=spec.settingName%EF%BC%9A-,%E6%8F%92%E4%BB%B6%E9%85%8D%E7%BD%AE%E8%A1%A8%E5%8D%95%E5%90%8D%E7%A7%B0,-%EF%BC%8C%E5%AF%B9%E5%BA%94%E4%B8%80%E4%B8%AA%20Setting)
在参考[评论插件设置资源定义 settings.yaml](https://github.com/halo-dev/plugin-comment-widget/blob/39655225592027b7f4a279527292e044d29322a8/src/main/resources/extensions/settings.yaml#L1)

2024-04-04 14:07 UTC, ruibaby commented on src/main/java/run/halo/comment/widget/CommentWidgetSetting.java
> +public class CommentWidgetSetting extends AbstractExtension {
关于如何将插件的设置交给前端，可以参考 https://github.com/halo-dev/plugin-comment-widget/pull/106/files 的做法。

> 这个项目好像没有引入vue

前端部分现在使用的是 https://lit.dev/

2024-04-04 14:09 UTC, ruibaby commented on src/main/java/run/halo/comment/widget/CommentWidgetSetting.java
> +public class CommentWidgetSetting extends AbstractExtension {
另外，我建议为 Gravatar 添加一个新的设置分组，比如**头像设置（avatar）**

2024-04-04 14:48 UTC, mashirot commented on src/main/java/run/halo/comment/widget/CommentWidgetSetting.java
> +public class CommentWidgetSetting extends AbstractExtension {
> 另外，我建议为 Gravatar 添加一个新的设置分组，比如**头像设置（avatar）**

这个改动能否另开一个issue，我已经在 `评论插件的设置表单` 中完成了功能

2024-04-07 03:08 UTC, ruibaby commented on src/main/java/run/halo/comment/widget/CommentWidgetSetting.java
> +public class CommentWidgetSetting extends AbstractExtension {
> > 另外，我建议为 Gravatar 添加一个新的设置分组，比如**头像设置（avatar）**
> 
> 这个改动能否另开一个issue，我已经在 `评论插件的设置表单` 中完成了功能

应该可以放在这个 PR 吧，毕竟是新增配置项，这样就好了：

```diff
apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-comment-widget-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $formkit: number
          label: 默认加载评论条数
          name: size
          validation: required
          value: 20
        - $formkit: number
          label: 默认加载回复条数
          name: replySize
          validation: required
          value: 10
        - $formkit: checkbox
          label: 同时加载评论的回复
          name: withReplies
          id: withReplies
          key: withReplies
          value: false
        - $formkit: number
          label: 同时加载回复的条数
          if: $get(withReplies).value === true
          name: withReplySize
          id: withReplySize
          key: withReplySize
          validation: required
          value: 5
+    - group: avatar
+      label: 头像设置
+      formSchema:
+        - $formkit: checkbox
+          label: 是否启用第三方头像
+          name: useAvatarProvider
+          id: useAvatarProvider
+          key: useAvatarProvider
+          value: false
+        - $formkit: select
+          label: 头像服务提供者
+          if: $get(useAvatarProvider).value === true
+          name: avatarProvider
+          options:
+            - label: Gravatar
+              value: Gravatar
+          value: Gravatar
+        - $formkit: text
+          label: 头像服务镜像地址
+          if: $get(useAvatarProvider).value === true
+          name: avatarProviderMirror
+          value: ''
+          help: 使用官方源则留空
+        - $formkit: select
+          label: 头像策略
+          if: $get(useAvatarProvider).value === true
+          name: avatarPolicy
+          options:
+            - label: 仅匿名用户
+              value: AnonymousUserPolicy
+            - label: 所有用户
+              value: AllUserPolicy
+            - label: 无头像已注册用户
+              value: NoAvatarUserPolicy
+          value: AnonymousUserPolicy
```

2024-04-07 08:40 UTC, mashirot commented
@ruibaby @guqing pls review

2024-04-08 07:30 UTC, guqing commented on src/main/java/run/halo/comment/widget/DefaultCommentWidget.java
> +        private String avatarProvider;
这里的 AvatarConfig  中的 avatar 前缀有些多余了建议直接去掉，需要同步改一下 settings.yaml 的命名

2024-04-08 07:42 UTC, guqing commented on src/main/java/run/halo/comment/widget/DefaultCommentWidget.java
> +        properties.setProperty("enable", String.valueOf(avatarConfig.isEnable()));
Hi @mashirot 这里的 avatar 前缀不用改，之前是限定在 AvatarConfig 类下的因此多余，但是这里是平铺，如果去掉前缀很不容易理解而且下次再加入其他变量容易名称冲突，造成不必要的改动

2024-04-08 10:27 UTC, ruibaby requested changes
感谢 @mashirot 的贡献，我已经实际测试，功能没有问题。但还有部分建议改进的地方，有时间可以看看。

2024-04-08 10:27 UTC, ruibaby commented on packages/comment-widget/src/avatar/providers/gravatar.ts
> +    return this.url + emailHash;
这里是否能提高一下容错率？即不管用户输入的尾部带不带 / 都可以正确生成链接。

另外，建议在 help 中给出一定的提示和示例（我设置了三次才猜成功 :)

<img width="660" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/21301288/44a25c05-1e25-4daf-a9b4-e09dd23c7c0f">

2024-04-08 10:27 UTC, ruibaby commented on src/main/resources/extensions/settings.yaml
> +            - label: '无头像已注册用户'
这个选项我建议重新定义为 **匿名用户 + 未设置头像的注册用户**，即三种策略：

1. 仅匿名用户：代表仅对匿名用户有效。
2. 所有用户：即便是注册用户，也生效。
3. 匿名用户 + 未设置头像的注册用户：匿名评论的用户和已经注册但是未设置头像的用户。

主要考虑目前的 **无头像已注册用户** 似乎没有这样的场景，而 **匿名用户 + 未设置头像的注册用户** 可以覆盖这个场景。

2024-04-08 10:27 UTC, ruibaby commented on src/main/resources/extensions/settings.yaml
> +              value: 'Gravatar'
```suggestion
              value: 'gravatar'
```

建议所有 **value** 都采用驼峰命名。

2024-04-08 10:27 UTC, ruibaby commented on src/main/resources/extensions/settings.yaml
> +              value: 'AnonymousUserPolicy'
```suggestion
              value: 'anonymousUserPolicy'
```

同上。另外，字段名已经是 `policy`，那么 value 我觉得可以忽略掉 `Policy`，直接使用 `anonymousUser`。

2024-04-08 10:27 UTC, ruibaby commented on src/main/resources/extensions/settings.yaml
> +              value: 'AllUserPolicy'
同上。

2024-04-08 10:27 UTC, ruibaby commented on src/main/resources/extensions/settings.yaml
> +          value: "AnonymousUserPolicy"
同上。

2024-04-08 10:27 UTC, ruibaby commented on packages/comment-widget/src/user-avatar.ts
> +export function handleCommentAvatar(comment: CommentVo | undefined): string | undefined {
这里的逻辑感觉不适合放置在这个组件中，除非组件有调用。这个组件应该只做头像加载和显示。

2024-04-08 10:27 UTC, ruibaby commented on packages/comment-widget/src/user-avatar.ts
> +export function handleCommentAvatar(comment: CommentVo | undefined): string | undefined {
可以考虑直接放在 comment-item 和 reply-item 组件中。

2024-04-08 10:27 UTC, ruibaby commented on packages/comment-widget/src/avatar-provider.ts
这个文件我建议直接放置到 `/avatar/providers`，并且命名为 index.ts

然后在调用方直接 `import { getAvatarProvider } from "/avatar/providers"`

2024-04-09 02:12 UTC, ruibaby reviewed
/lgtm

已测试，符合预期。

再次感谢 @mashirot 的贡献，这帮助社区解决了从 Halo 2.0 到现在的一个问题。

2024-04-09 02:29 UTC, JohnNiang approved these changes
/approve

Thanks for your first contribution!

2024-04-09 02:30 UTC, merged

2024-04-09 02:43 UTC, JohnNiang commented
当前 PR 可能缺少对于 Halo 版本（>= 2.15）的限制。