pref: add --component-comment-item-meta-info-color var
halo-dev/plugin-comment-widget pull request #89
Opened 2024-03-05 15:17 UTC by AirboZH

增加变量以适配主题颜色

测试添加变量成功
![image](https://github.com/halo-dev/plugin-comment-widget/assets/50261327/e72f0534-d17e-4411-aac9-185005ddf2af)

2024-03-06 02:30 UTC, ruibaby commented
我们是否可以直接新建一个统一的变量，命名为 `base-info-color` 或者 `base-accent-color`，用于为非重要突出的文字统一设置颜色。

2024-03-06 04:27 UTC, AirboZH commented
> 我们是否可以直接新建一个统一的变量，命名为 `base-info-color` 或者 `base-accent-color`，用于为非重要突出的文字统一设置颜色。

没问题！除了这个 meta-info 还有什么字段是 非重要突出文字 呢

2024-03-06 04:30 UTC, ruibaby commented
> > 我们是否可以直接新建一个统一的变量，命名为 `base-info-color` 或者 `base-accent-color`，用于为非重要突出的文字统一设置颜色。
> 
> 没问题！除了这个 meta-info 还有什么字段是 非重要突出文字 呢

比如列表项中的点赞、回复按钮的图标和文字默认颜色，改为 base-info-color 变量之后，hover 的时候可以设置为 base-color。

<img width="75" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/21301288/3a9d1a9b-91b4-46c0-9a13-ad2be2c74f88">

还有 Emoji 图标同上。

<img width="39" alt="image" src="https://github.com/halo-dev/plugin-comment-widget/assets/21301288/e61bf66f-4fe9-41c8-a5be-8df29baa396a">

2024-03-06 11:35 UTC, AirboZH commented
我认为列表项中的点赞、回复按钮的图标和文字默认颜色可以设置为 `base-info-color ` 但是 Emoji 图标还是和左侧用户名颜色对齐可能更好些。

![image](https://github.com/halo-dev/plugin-comment-widget/assets/50261327/5554b5e8-cf93-4afc-a6ff-83e8baf585d6)
![image](https://github.com/halo-dev/plugin-comment-widget/assets/50261327/fa148ba3-12c8-4187-8871-8f0b346312a9)

2024-03-07 07:20 UTC, ruibaby requested changes

2024-03-07 07:20 UTC, ruibaby commented on README.md
> +| `--halo-comment-widget-base-info-bg-color-hover`                        | 非重要突出文字悬停背景颜色 |
感觉这个变量的意义有点奇怪，点赞按钮和回复按钮的悬停背景色建议和以前保持一致。

2024-03-07 07:20 UTC, ruibaby commented on README.md
> +  --halo-comment-widget-base-info-bg-color-hover: #475569;
```suggestion
  --halo-comment-widget-base-info-color: ;
  --halo-comment-widget-base-info-color-hover: ;
  --halo-comment-widget-base-info-bg-color-hover: ;
```

2024-03-08 03:23 UTC, ruibaby approved these changes
/lgtm

感谢 @AirboZH 的贡献。

2024-03-08 03:24 UTC, merged